import political_science_authoritarian_politics_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace political_science_authoritarian_politics_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end political_science_authoritarian_politics_foundation_canonical_lane_mathlib
end HautevilleHouse
